/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIAgentMetrics {
  'falseNegativeRate' : number,
  'validationAccuracy' : number,
  'falsePositiveRate' : number,
  'averageProcessingTime' : bigint,
  'confidenceScores' : Array<number>,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Booking {
  'status' : BookingStatus,
  'serviceType' : string,
  'provider' : Principal,
  'participant' : Principal,
  'price' : bigint,
  'timeSlot' : TimeSlot,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface BudgetCategory {
  'name' : string,
  'spent' : bigint,
  'amount' : bigint,
}
export interface BudgetThresholdAlert {
  'threshold' : bigint,
  'utilized' : bigint,
  'participant' : Principal,
  'timestamp' : bigint,
  'category' : string,
}
export interface BudgetValidationResult {
  'reasons' : Array<string>,
  'valid' : boolean,
  'warnings' : Array<string>,
  'recommendedAdjustments' : Array<[string, bigint]>,
  'predictedDepletionDate' : [] | [bigint],
}
export interface EvidenceDocument {
  'id' : string,
  'provider' : Principal,
  'file' : ExternalBlob,
  'participant' : Principal,
  'category' : string,
}
export type ExternalBlob = Uint8Array;
export interface Guardian { 'participant' : Principal }
export interface Invoice {
  'status' : InvoiceStatus,
  'provider' : Principal,
  'participant' : Principal,
  'totalAmount' : bigint,
  'number' : string,
  'items' : Array<InvoiceLineItem>,
}
export interface InvoiceLineItem {
  'description' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type InvoiceStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface NDISPlan {
  'categories' : Array<[string, BudgetCategory]>,
  'status' : PlanStatus,
  'endDate' : bigint,
  'participant' : Principal,
  'planNumber' : string,
  'goals' : Array<string>,
  'document' : [] | [ExternalBlob],
  'startDate' : bigint,
}
export interface Participant {
  'ndisNumber' : string,
  'age' : bigint,
  'name' : string,
  'address' : string,
  'primaryContact' : string,
  'planManager' : Principal,
}
export interface PlanManager { 'provider' : Principal }
export type PlanStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'pendingApproval' : null };
export interface ServiceProvider {
  'abn' : string,
  'principal' : Principal,
  'ndisVerified' : boolean,
  'name' : string,
  'availability' : Array<TimeSlot>,
  'summary' : string,
  'rating' : [] | [bigint],
  'priceList' : Array<[string, bigint]>,
  'serviceTypes' : Array<string>,
}
export interface TimeSlot { 'end' : bigint, 'start' : bigint }
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAvailability' : ActorMethod<[Principal, Array<TimeSlot>], undefined>,
  'addServiceProvider' : ActorMethod<[ServiceProvider], undefined>,
  'approveInvoice' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmBooking' : ActorMethod<[Booking], undefined>,
  'createBooking' : ActorMethod<[Booking], undefined>,
  'createInvoice' : ActorMethod<[Invoice], undefined>,
  'detectAnomalies' : ActorMethod<[Principal], Array<string>>,
  'getAIAgentMetrics' : ActorMethod<[], AIAgentMetrics>,
  'getAllParticipants' : ActorMethod<[], Array<Participant>>,
  'getAllPlans' : ActorMethod<[], Array<NDISPlan>>,
  'getAllProviders' : ActorMethod<[], Array<ServiceProvider>>,
  'getAvailableProviders' : ActorMethod<[string], Array<string>>,
  'getBudgetThresholdAlerts' : ActorMethod<
    [Principal],
    Array<BudgetThresholdAlert>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuardian' : ActorMethod<[Principal], Guardian>,
  'getParticipant' : ActorMethod<[Principal], Participant>,
  'getParticipantBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getParticipantEvidence' : ActorMethod<[Principal], Array<EvidenceDocument>>,
  'getParticipantInvoices' : ActorMethod<[Principal], Array<Invoice>>,
  'getParticipantPlans' : ActorMethod<[Principal], Array<NDISPlan>>,
  'getPlanManager' : ActorMethod<[Principal], PlanManager>,
  'getProvider' : ActorMethod<[Principal], ServiceProvider>,
  'getProviderBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getProviderInvoices' : ActorMethod<[Principal], Array<Invoice>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handleBudgetUtilization' : ActorMethod<
    [bigint, Principal, string],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'recordValidationFeedback' : ActorMethod<
    [Principal, string, boolean, string],
    undefined
  >,
  'registerGuardian' : ActorMethod<[Guardian], undefined>,
  'registerParticipant' : ActorMethod<[Participant], undefined>,
  'registerPlanManager' : ActorMethod<[PlanManager], undefined>,
  'registerServiceProvider' : ActorMethod<[ServiceProvider], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProviders' : ActorMethod<[string], Array<string>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateAIValidationThresholds' : ActorMethod<
    [Array<[string, number]>],
    undefined
  >,
  'updateCategorySpending' : ActorMethod<
    [Principal, string, bigint],
    undefined
  >,
  'uploadEvidence' : ActorMethod<[EvidenceDocument], undefined>,
  'uploadPlan' : ActorMethod<[ExternalBlob], undefined>,
  'validateBudgetTransaction' : ActorMethod<
    [Principal, string, bigint],
    BudgetValidationResult
  >,
  'validateCompliance' : ActorMethod<[Principal, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];