/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Participant {
    ndisNumber: string;
    age: bigint;
    name: string;
    address: string;
    primaryContact: string;
    planManager: Principal;
}
export interface TimeSlot {
    end: bigint;
    start: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BudgetValidationResult {
    reasons: Array<string>;
    valid: boolean;
    warnings: Array<string>;
    recommendedAdjustments: Array<[string, bigint]>;
    predictedDepletionDate?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface BudgetCategory {
    name: string;
    spent: bigint;
    amount: bigint;
}
export interface Invoice {
    status: InvoiceStatus;
    provider: Principal;
    participant: Principal;
    totalAmount: bigint;
    number: string;
    items: Array<InvoiceLineItem>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface NDISPlan {
    categories: Array<[string, BudgetCategory]>;
    status: PlanStatus;
    endDate: bigint;
    participant: Principal;
    planNumber: string;
    goals: Array<string>;
    document?: ExternalBlob;
    startDate: bigint;
}
export interface AIAgentMetrics {
    falseNegativeRate: number;
    validationAccuracy: number;
    falsePositiveRate: number;
    averageProcessingTime: bigint;
    confidenceScores: Array<number>;
}
export interface EvidenceDocument {
    id: string;
    provider: Principal;
    file: ExternalBlob;
    participant: Principal;
    category: string;
}
export interface BudgetThresholdAlert {
    threshold: bigint;
    utilized: bigint;
    participant: Principal;
    timestamp: bigint;
    category: string;
}
export interface Guardian {
    participant: Principal;
}
export interface Booking {
    status: BookingStatus;
    serviceType: string;
    provider: Principal;
    participant: Principal;
    price: bigint;
    timeSlot: TimeSlot;
}
export interface PlanManager {
    provider: Principal;
}
export interface InvoiceLineItem {
    description: string;
    quantity: bigint;
    price: bigint;
}
export interface ServiceProvider {
    abn: string;
    principal: Principal;
    ndisVerified: boolean;
    name: string;
    availability: Array<TimeSlot>;
    summary: string;
    rating?: bigint;
    priceList: Array<[string, bigint]>;
    serviceTypes: Array<string>;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum InvoiceStatus {
    pending = "pending",
    paid = "paid",
    approved = "approved",
    rejected = "rejected"
}
export enum PlanStatus {
    active = "active",
    expired = "expired",
    pendingApproval = "pendingApproval"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAvailability(provider: Principal, timeSlots: Array<TimeSlot>): Promise<void>;
    addServiceProvider(provider: ServiceProvider): Promise<void>;
    approveInvoice(participant: Principal, invoiceNumber: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmBooking(booking: Booking): Promise<void>;
    createBooking(booking: Booking): Promise<void>;
    createInvoice(invoice: Invoice): Promise<void>;
    detectAnomalies(participant: Principal): Promise<Array<string>>;
    getAIAgentMetrics(): Promise<AIAgentMetrics>;
    getAllParticipants(): Promise<Array<Participant>>;
    getAllPlans(): Promise<Array<NDISPlan>>;
    getAllProviders(): Promise<Array<ServiceProvider>>;
    getAvailableProviders(serviceType: string): Promise<Array<string>>;
    getBudgetThresholdAlerts(participant: Principal): Promise<Array<BudgetThresholdAlert>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGuardian(guardian: Principal): Promise<Guardian>;
    getParticipant(participant: Principal): Promise<Participant>;
    getParticipantBookings(participant: Principal): Promise<Array<Booking>>;
    getParticipantEvidence(participant: Principal): Promise<Array<EvidenceDocument>>;
    getParticipantInvoices(participant: Principal): Promise<Array<Invoice>>;
    getParticipantPlans(participant: Principal): Promise<Array<NDISPlan>>;
    getPlanManager(planManager: Principal): Promise<PlanManager>;
    getProvider(provider: Principal): Promise<ServiceProvider>;
    getProviderBookings(provider: Principal): Promise<Array<Booking>>;
    getProviderInvoices(provider: Principal): Promise<Array<Invoice>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    handleBudgetUtilization(utilizedAmount: bigint, participant: Principal, category: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    recordValidationFeedback(participant: Principal, transactionId: string, approved: boolean, reason: string): Promise<void>;
    registerGuardian(guardian: Guardian): Promise<void>;
    registerParticipant(participant: Participant): Promise<void>;
    registerPlanManager(planManager: PlanManager): Promise<void>;
    registerServiceProvider(provider: ServiceProvider): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProviders(serviceType: string): Promise<Array<string>>;
    updateAIValidationThresholds(thresholds: Array<[string, number]>): Promise<void>;
    updateCategorySpending(participant: Principal, category: string, amount: bigint): Promise<void>;
    uploadEvidence(doc: EvidenceDocument): Promise<void>;
    uploadPlan(document: ExternalBlob): Promise<void>;
    validateBudgetTransaction(participant: Principal, category: string, amount: bigint): Promise<BudgetValidationResult>;
    validateCompliance(participant: Principal, invoiceNumber: string): Promise<boolean>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, BudgetCategory as _BudgetCategory, BudgetValidationResult as _BudgetValidationResult, EvidenceDocument as _EvidenceDocument, ExternalBlob as _ExternalBlob, Invoice as _Invoice, InvoiceLineItem as _InvoiceLineItem, InvoiceStatus as _InvoiceStatus, NDISPlan as _NDISPlan, PlanStatus as _PlanStatus, ServiceProvider as _ServiceProvider, TimeSlot as _TimeSlot, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAvailability(arg0: Principal, arg1: Array<TimeSlot>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAvailability(arg0, arg1);
            return result;
        }
    }
    async addServiceProvider(arg0: ServiceProvider): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceProvider(to_candid_ServiceProvider_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceProvider(to_candid_ServiceProvider_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveInvoice(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveInvoice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveInvoice(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBooking(to_candid_Booking_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBooking(to_candid_Booking_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_Booking_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_Booking_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_Invoice_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_Invoice_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async detectAnomalies(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.detectAnomalies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detectAnomalies(arg0);
            return result;
        }
    }
    async getAIAgentMetrics(): Promise<AIAgentMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIAgentMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIAgentMetrics();
            return result;
        }
    }
    async getAllParticipants(): Promise<Array<Participant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParticipants();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParticipants();
            return result;
        }
    }
    async getAllPlans(): Promise<Array<NDISPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlans();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlans();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProviders(): Promise<Array<ServiceProvider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProviders();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProviders();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableProviders(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableProviders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableProviders(arg0);
            return result;
        }
    }
    async getBudgetThresholdAlerts(arg0: Principal): Promise<Array<BudgetThresholdAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetThresholdAlerts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetThresholdAlerts(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuardian(arg0: Principal): Promise<Guardian> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuardian(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuardian(arg0);
            return result;
        }
    }
    async getParticipant(arg0: Principal): Promise<Participant> {
        if (this.processError) {
            try {
                const result = await this.actor.getParticipant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParticipant(arg0);
            return result;
        }
    }
    async getParticipantBookings(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParticipantBookings(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParticipantBookings(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParticipantEvidence(arg0: Principal): Promise<Array<EvidenceDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParticipantEvidence(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParticipantEvidence(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParticipantInvoices(arg0: Principal): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParticipantInvoices(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParticipantInvoices(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParticipantPlans(arg0: Principal): Promise<Array<NDISPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParticipantPlans(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParticipantPlans(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlanManager(arg0: Principal): Promise<PlanManager> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanManager(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanManager(arg0);
            return result;
        }
    }
    async getProvider(arg0: Principal): Promise<ServiceProvider> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return from_candid_ServiceProvider_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return from_candid_ServiceProvider_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderBookings(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderBookings(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderBookings(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderInvoices(arg0: Principal): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderInvoices(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderInvoices(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async handleBudgetUtilization(arg0: bigint, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleBudgetUtilization(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleBudgetUtilization(arg0, arg1, arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordValidationFeedback(arg0: Principal, arg1: string, arg2: boolean, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordValidationFeedback(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordValidationFeedback(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async registerGuardian(arg0: Guardian): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerGuardian(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerGuardian(arg0);
            return result;
        }
    }
    async registerParticipant(arg0: Participant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerParticipant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerParticipant(arg0);
            return result;
        }
    }
    async registerPlanManager(arg0: PlanManager): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPlanManager(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPlanManager(arg0);
            return result;
        }
    }
    async registerServiceProvider(arg0: ServiceProvider): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerServiceProvider(to_candid_ServiceProvider_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerServiceProvider(to_candid_ServiceProvider_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchProviders(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProviders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProviders(arg0);
            return result;
        }
    }
    async updateAIValidationThresholds(arg0: Array<[string, number]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAIValidationThresholds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAIValidationThresholds(arg0);
            return result;
        }
    }
    async updateCategorySpending(arg0: Principal, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategorySpending(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategorySpending(arg0, arg1, arg2);
            return result;
        }
    }
    async uploadEvidence(arg0: EvidenceDocument): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadEvidence(await to_candid_EvidenceDocument_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadEvidence(await to_candid_EvidenceDocument_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadPlan(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPlan(await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPlan(await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async validateBudgetTransaction(arg0: Principal, arg1: string, arg2: bigint): Promise<BudgetValidationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.validateBudgetTransaction(arg0, arg1, arg2);
                return from_candid_BudgetValidationResult_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateBudgetTransaction(arg0, arg1, arg2);
            return from_candid_BudgetValidationResult_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateCompliance(arg0: Principal, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCompliance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCompliance(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetValidationResult_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetValidationResult): BudgetValidationResult {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_EvidenceDocument_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EvidenceDocument): Promise<EvidenceDocument> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InvoiceStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_NDISPlan_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NDISPlan): Promise<NDISPlan> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PlanStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanStatus): PlanStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceProvider_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceProvider): ServiceProvider {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories: Array<[string, _BudgetCategory]>;
    status: _PlanStatus;
    endDate: bigint;
    participant: Principal;
    planNumber: string;
    goals: Array<string>;
    document: [] | [_ExternalBlob];
    startDate: bigint;
}): Promise<{
    categories: Array<[string, BudgetCategory]>;
    status: PlanStatus;
    endDate: bigint;
    participant: Principal;
    planNumber: string;
    goals: Array<string>;
    document?: ExternalBlob;
    startDate: bigint;
}> {
    return {
        categories: value.categories,
        status: from_candid_PlanStatus_n23(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        participant: value.participant,
        planNumber: value.planNumber,
        goals: value.goals,
        document: record_opt_to_undefined(await from_candid_opt_n25(_uploadFile, _downloadFile, value.document)),
        startDate: value.startDate
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    abn: string;
    principal: Principal;
    ndisVerified: boolean;
    name: string;
    availability: Array<_TimeSlot>;
    summary: string;
    rating: [] | [bigint];
    priceList: Array<[string, bigint]>;
    serviceTypes: Array<string>;
}): {
    abn: string;
    principal: Principal;
    ndisVerified: boolean;
    name: string;
    availability: Array<TimeSlot>;
    summary: string;
    rating?: bigint;
    priceList: Array<[string, bigint]>;
    serviceTypes: Array<string>;
} {
    return {
        abn: value.abn,
        principal: value.principal,
        ndisVerified: value.ndisVerified,
        name: value.name,
        availability: value.availability,
        summary: value.summary,
        rating: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.rating)),
        priceList: value.priceList,
        serviceTypes: value.serviceTypes
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    serviceType: string;
    provider: Principal;
    participant: Principal;
    price: bigint;
    timeSlot: _TimeSlot;
}): {
    status: BookingStatus;
    serviceType: string;
    provider: Principal;
    participant: Principal;
    price: bigint;
    timeSlot: TimeSlot;
} {
    return {
        status: from_candid_BookingStatus_n36(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        provider: value.provider,
        participant: value.participant,
        price: value.price,
        timeSlot: value.timeSlot
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    provider: Principal;
    file: _ExternalBlob;
    participant: Principal;
    category: string;
}): Promise<{
    id: string;
    provider: Principal;
    file: ExternalBlob;
    participant: Principal;
    category: string;
}> {
    return {
        id: value.id,
        provider: value.provider,
        file: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.file),
        participant: value.participant,
        category: value.category
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _InvoiceStatus;
    provider: Principal;
    participant: Principal;
    totalAmount: bigint;
    number: string;
    items: Array<_InvoiceLineItem>;
}): {
    status: InvoiceStatus;
    provider: Principal;
    participant: Principal;
    totalAmount: bigint;
    number: string;
    items: Array<InvoiceLineItem>;
} {
    return {
        status: from_candid_InvoiceStatus_n44(_uploadFile, _downloadFile, value.status),
        provider: value.provider,
        participant: value.participant,
        totalAmount: value.totalAmount,
        number: value.number,
        items: value.items
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reasons: Array<string>;
    valid: boolean;
    warnings: Array<string>;
    recommendedAdjustments: Array<[string, bigint]>;
    predictedDepletionDate: [] | [bigint];
}): {
    reasons: Array<string>;
    valid: boolean;
    warnings: Array<string>;
    recommendedAdjustments: Array<[string, bigint]>;
    predictedDepletionDate?: bigint;
} {
    return {
        reasons: value.reasons,
        valid: value.valid,
        warnings: value.warnings,
        recommendedAdjustments: value.recommendedAdjustments,
        predictedDepletionDate: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.predictedDepletionDate))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    pendingApproval: null;
}): PlanStatus {
    return "active" in value ? PlanStatus.active : "expired" in value ? PlanStatus.expired : "pendingApproval" in value ? PlanStatus.pendingApproval : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    approved: null;
} | {
    rejected: null;
}): InvoiceStatus {
    return "pending" in value ? InvoiceStatus.pending : "paid" in value ? InvoiceStatus.paid : "approved" in value ? InvoiceStatus.approved : "rejected" in value ? InvoiceStatus.rejected : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NDISPlan>): Promise<Array<NDISPlan>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NDISPlan_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceProvider>): Array<ServiceProvider> {
    return value.map((x)=>from_candid_ServiceProvider_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n34(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EvidenceDocument>): Promise<Array<EvidenceDocument>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EvidenceDocument_n39(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n42(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Booking_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Booking): _Booking {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_EvidenceDocument_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EvidenceDocument): Promise<_EvidenceDocument> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InvoiceStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceProvider_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceProvider): _ServiceProvider {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: BookingStatus;
    serviceType: string;
    provider: Principal;
    participant: Principal;
    price: bigint;
    timeSlot: TimeSlot;
}): {
    status: _BookingStatus;
    serviceType: string;
    provider: Principal;
    participant: Principal;
    price: bigint;
    timeSlot: _TimeSlot;
} {
    return {
        status: to_candid_BookingStatus_n14(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        provider: value.provider,
        participant: value.participant,
        price: value.price,
        timeSlot: value.timeSlot
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: InvoiceStatus;
    provider: Principal;
    participant: Principal;
    totalAmount: bigint;
    number: string;
    items: Array<InvoiceLineItem>;
}): {
    status: _InvoiceStatus;
    provider: Principal;
    participant: Principal;
    totalAmount: bigint;
    number: string;
    items: Array<_InvoiceLineItem>;
} {
    return {
        status: to_candid_InvoiceStatus_n18(_uploadFile, _downloadFile, value.status),
        provider: value.provider,
        participant: value.participant,
        totalAmount: value.totalAmount,
        number: value.number,
        items: value.items
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    provider: Principal;
    file: ExternalBlob;
    participant: Principal;
    category: string;
}): Promise<{
    id: string;
    provider: Principal;
    file: _ExternalBlob;
    participant: Principal;
    category: string;
}> {
    return {
        id: value.id,
        provider: value.provider,
        file: await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.file),
        participant: value.participant,
        category: value.category
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    abn: string;
    principal: Principal;
    ndisVerified: boolean;
    name: string;
    availability: Array<TimeSlot>;
    summary: string;
    rating?: bigint;
    priceList: Array<[string, bigint]>;
    serviceTypes: Array<string>;
}): {
    abn: string;
    principal: Principal;
    ndisVerified: boolean;
    name: string;
    availability: Array<_TimeSlot>;
    summary: string;
    rating: [] | [bigint];
    priceList: Array<[string, bigint]>;
    serviceTypes: Array<string>;
} {
    return {
        abn: value.abn,
        principal: value.principal,
        ndisVerified: value.ndisVerified,
        name: value.name,
        availability: value.availability,
        summary: value.summary,
        rating: value.rating ? candid_some(value.rating) : candid_none(),
        priceList: value.priceList,
        serviceTypes: value.serviceTypes
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    pending: null;
} | {
    paid: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == InvoiceStatus.pending ? {
        pending: null
    } : value == InvoiceStatus.paid ? {
        paid: null
    } : value == InvoiceStatus.approved ? {
        approved: null
    } : value == InvoiceStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
